#cloud-config
write_files:
- path: /etc/carbon/git-repos
  content: |
    https://github.com/defektive/redteam-tips.git
    https://gitlab.com/exploit-database/exploitdb.git
    https://github.com/Pennyw0rth/NetExec.git
  owner: 'root:root'
  permissions: '0o644'
- path: /etc/carbon/github-releases
  content: |
    owasp-amass/amass
    gohugoio/hugo extended
  owner: 'root:root'
  permissions: '0o644'
- path: /etc/carbon/go-installs
  content: |
    github.com/analog-substance/nex@latest
    github.com/analog-substance/as-gold@latest
    github.com/analog-substance/copper/cmd/copper@latest
    github.com/defektive/fast-resolv@latest
    github.com/OJ/gobuster/v3@latest
    github.com/ffuf/ffuf@latest
    github.com/hakluke/hakrawler@latest
    github.com/hakluke/hakcheckurl@latest
    github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest
    github.com/projectdiscovery/httpx/cmd/httpx@latest
    github.com/projectdiscovery/dnsx/cmd/dnsx@latest
    github.com/projectdiscovery/katana/cmd/katana@latest
    github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
    github.com/sensepost/gowitness@latest
    github.com/projectdiscovery/cdncheck/cmd/cdncheck@latest
  owner: 'root:root'
  permissions: '0o644'
- path: /usr/local/bin/carbon-init.sh
  # this is files/var/carbon/carbon-init.sh needs to be automated
  content: !!binary |
    H4sIAAAAAAAAA8VXbW/bNhD+PP+Kq2rM9jqJc9GlQwJ1C9K0DdB2QdENBZJMoCnaUiORqijZjpP89x1JWS+OkvZDhxkIYt8dj/f+HB8/AjKLBZlRFQ0+vjsNXp58CE4/HL86+eQ7JC8FYTSfSeEMBvNSsCKWAgqeZkEY50Es4gLGE7geAH7SS6SBm8Gwq4cMp4bPwj7ObZ9ilnAqGs140oWnL36cwgsgIV8SUSaJ4eQpuPn8Hr2N4liogiZJIKP0aqOiRnM8hzN4BG4IhBeMqEueEE9GbnrlarmLAygiLoyo/izQX5ZIwcFlwGTOPVoWkuXJ3I9FVhbguiHPisifQlQUmdonBI9E5cxjMiW5nM2u8lIpniSkvsTTSvtuN7fO406EREqzIMvjZZzwBVeNIwoV0AzwLxC8CHK6+nn7nYZpLOpfmOwwUDxfxow/4XEGpFS5KQGt2+jiLJLg8HUm8wLevzs8xbCe/H3y9vj18Ut/6ugkNOaioTnzQlJbpiypY/ZMykIVOUqUeHVjda6uBAOXthQCiWTKSTkrRVFiPPmaJWXIwVsKZoshkisB7gewIvuVZPtYJYcJdFXjn05oxb/tqY2FbOzqVvjw1V/vj94fvjseGOZCBmWe+E6dYZlQsfBkviBhQoZjhlx98agR8HTRIvP3VIbc/6ykGMENfP6CxQsj7+yXC2/Jc4XWjCZeEoty7dI03HvmFTT3FhvH+mPUSry+RwTctwqcoTXNabeGcT+RjCZoh3WOYpcetRjgrjfzfr2DbjhsXzbxaMcRK7DMApn1TQSCZLweehOoylAaiS0bg6TZz5//2iKj+jlliWa4KSzMqf189cmIHGCfiNBKu8VVxgE18DVnO8fC/dZB5/rWgfODjhOmuYOcZ61iaDW97W6Yws7g2tYQzRUXMXv4bM9koIImcuGqcoZ6BOOkUmRngw5eRdiOwzu0138eHR69OfarSBOPURZxJJ8efnyzpXaLwTQFEivj60nb8QwrquI3Tgmacn84Rsjg+isGA4uZ6ekXwuiPEbjz6eQ7GQXuUqs3s/8Gk4kXKPIPORs5Q321M7oAMupvZxNdTCWWrOJfb+2qxuAJt92DJeBXwKU4zVnkD5/abpDKH5lOGVkIQT0xTYJ5nBQ89x3TzhSHfKHOLpxekWGXYDxLOCvGY88E9AaoYnEchNgoTFuP4ZWioOjb+NwZSnXuTCYTZ1BD2Bn2/rg0Z9104oDvg7P+bS/Ye+bAxS6IfV9rzLSw9sBjkDjcv+XU3rNZXFReVDDXweMNOmTD7twBYQtPNMu4CGOxgMrsOd69PfMf+Vqp77E758pvJn8NDTSLvfYCgEWlyFD/I1VhKqcGgh7jvFkuV4iYxp5E0tCMd9tcmzjDK20wUKVRtEDVcO4ha7Id9f0y7ik453rGn+OQv8FviDL2SMhn96lF1mTQHeyOccbZzo72T91MLr+bVjSuzikMfrA3VV2r04l8GGupSZPGLfZVYtrBCvG0tlqsFJrREhrULIMPXgUOcwsOZUFnCa+AIl3C9W17FulBpOHBlFzS9gDD9qAHGmDHWuoBD4oas7W2Wsxg83qznLcF/x8vMNvohc75/V5oGesFfmvEwuxyAW7cFtt2i/7XIE1nID+0XDRLWlBImbQWX932moQigB1Iq13avloQSdzqqJocQCibTb7BNQwFnrfWhwjV3wAnrfvv3GgE3VrwBlYRLus4IWgIGFjeMUPfvG23oebqCbS6hNE1rtIC8Wl6O5rU0lsgekD+aVv+HiysHG5G7FddNxuR6jzINHrXCTALU38C4sI1h7vhb+1Z7ZlhbKiro3fDWikslLgxZbXAOVPP25VCpkdTupECf9jlyhB1f7h2wbXIaIbIoBkbD4ntPjvtjvpkrQ+RbR0Zzh1CtYYj/aedTROrPSiz1mOo9y3b2eU7e9ROfDBL3cfVzqPXrm7d96OhdR9nHa0pAl/njaknev113bmmel3Uz4BBvfpYvW3ZKotdWrXN7ii1/d4ldntxl2eL1eapCrJ2qogR37VDg38BDRLw6PQQAAA=
  owner: 'root:root'
  encoding: gzip
  permissions: '0o755'
- path: /etc/skel/.ssh/rc
  content: |
    #!/bin/bash

    # Fix SSH auth socket location so agent forwarding works with tmux
    if test "$SSH_AUTH_SOCK" ; then
        ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
    fi
  owner: 'root:root'
  permissions: '0o644'

- path: /etc/skel/.gitconfig
  content: |
    [safe]
      directory = /opt/arsenic
      directory = /opt/redteam-tips
      directory = /opt/exploitdb
      directory = /opt/NetExec
  owner: 'root:root'
  permissions: '0o644'

- path: /etc/skel/.tmux.conf
  content: |
    # Remove SSH_AUTH_SOCK to disable tmux automatically resetting the variable
    set -g update-environment "DISPLAY SSH_ASKPASS SSH_AGENT_PID \
                              SSH_CONNECTION WINDOWID XAUTHORITY"

    # Use a symlink to look up SSH authentication
    setenv -g SSH_AUTH_SOCK $HOME/.ssh/ssh_auth_sock

  owner: 'root:root'
  permissions: '0o644'

- path: /etc/skel/.zshrc
  content: |
    export ZSH=$HOME/.oh-my-zsh
    export NMAP_PRIVILEGED=""

    ZSH_THEME="robbyrussell"
    plugins=(git wd)

    source $ZSH/oh-my-zsh.sh

    ls  ~/.zshrc.d/*.zshrc | sort -n | while read f; do
      source "$f";
    done

  owner: 'root:root'
  permissions: '0o644'

- path: /etc/skel/.zshrc.d/carbon.zshrc
  content: |
    idempotent_path_prepend ()
    {
        PATH=${PATH//":$1"/} #delete any instances in the middle or at the end
        PATH=${PATH//"$1:"/} #delete any instances at the beginning
        export PATH="$1:$PATH" #prepend
    }

    export GOPATH="/opt/go"

    if [ -d /usr/local/go/bin ]; then
      idempotent_path_prepend /usr/local/go/bin
    fi

    if [ -d /opt/go/bin ]; then
      idempotent_path_prepend /opt/go/bin
    fi

    if [ -d "$HOME/.local/bin" ]; then
      idempotent_path_prepend $HOME/.local/bin
    fi

    if [ -d "$HOME/bin" ]; then
      idempotent_path_prepend $HOME/bin
    fi

    if test "$SSH_AUTH_SOCK" ; then
      if [ "$SSH_AUTH_SOCK" != "$HOME/.ssh/ssh_auth_sock" ]; then
        export SSH_AUTH_SOCK="$HOME/.ssh/ssh_auth_sock"
      fi
    fi

    if [ -f /opt/arsenic/arsenic.rc ]; then
      source /opt/arsenic/arsenic.rc
    fi

    if which arsenic > /dev/null 2>&1 ; then
      if [ ! -f "${fpath[1]}/_arsenic" ]; then
        arsenic completion zsh >  "${fpath[1]}/_arsenic"
      fi
    fi
    autoload -U compinit; compinit

  owner: 'root:root'
  permissions: '0o644'
