machines: []
#machines:
#  - name: xodbox
#    provider: digitalocean
#    type: s-1vcpu-512mb-10gb
#    region: sfo3
#    image: ubuntu-2404
#    purpose: app
#  - name: op001
#    provider: vsphere
#    type: s-1vcpu-512mb-10gb
#    region: sfo3
#    image: ubuntu-2404
#    purpose: app
